name: Build and publish a 🛢️ container

on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - 'main'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Build PuppetDB 7 container
        uses: voxpupuli/gha-build-and-publish-a-container@v2
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          build_args: 'PUPPET_RELEASE=7,PUPPET_VERSION=${{ github.ref_name }}}}'
          build_arch: linux/amd64,linux/arm64
          buildfile: 'puppetdb/Dockerfile'
        if: ${{ startsWith(github.ref_name, '7') }}

      - name: Build PuppetDB 8 container
        uses: voxpupuli/gha-build-and-publish-a-container@v2
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          build_args: 'PUPPET_RELEASE=8,PUPPET_VERSION=${{ github.ref_name }}}}'
          build_arch: linux/amd64,linux/arm64
          buildfile: 'puppetdb/Dockerfile'
        if: ${{ startsWith(github.ref_name, '8') }}
