name: Build and publish a 🛢️ container

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Source checkout
        uses: actions/checkout@v4

      - id: set-matrix
        run: echo "matrix=$(cat build_versions.json | jq -c)" >> $GITHUB_OUTPUT

  build-and-push-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      - name: Build PuppetDB ${{ matrix.release }} container
        uses: voxpupuli/gha-build-and-publish-a-container@v2
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          build_args: |
            PUPPET_RELEASE=${{ matrix.release }}
            PUPPETDB_VERSION=${{ matrix.version }}
          build_arch: linux/amd64,linux/arm64
          docker_username: voxpupulibot
          docker_password: ${{ secrets.DOCKERHUB_BOT_PASSWORD }}
          build_context: puppetdb
          buildfile: puppetdb/Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}:v${{ matrix.version }}-${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
            docker.io/${{ github.repository }}:v${{ matrix.version }}-${{ github.ref_name }}
            docker.io/${{ github.repository }}:latest

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: voxpupulibot
          password: ${{ secrets.DOCKERHUB_BOT_PASSWORD }}
